name: Update CVE Data

on:
  schedule:
    - cron: '0 0 * * *' # run once a day
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout main branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: setup python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/update-cve-data-requirements.txt

      - name: execute python script
        run: python tools/update-cve-data.py /tmp/published_output.json

      - name: push data to data-source branch
        run: |
          git fetch origin data-source
          git checkout data-source
          cp /tmp/published_output.json .
          git add published_output.json

          if ! git diff --cached --quiet; then
            git config user.name otelbot
            git config user.email 197425009+otelbot@users.noreply.github.com
            git commit -m "Update CVE data"
            git push origin data-source
          fi
