name: Update CVE Data

on:
  schedule:
    - cron: '0 0 * * *' # run once a day
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout main branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.14'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/update-cve-data-requirements.txt

      - name: execute python script
        env:
          # this is only needed here for higher API rate limits
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python tools/update-cve-data.py /tmp/published_output.json

      - name: push data to data-source branch
        run: |
          git fetch origin data-source
          git checkout data-source
          cp /tmp/published_output.json .
          git add published_output.json

          if ! git diff --cached --quiet; then
            git config user.name otelbot
            git config user.email 197425009+otelbot@users.noreply.github.com
            git commit -m "Update CVE data"
            git push origin data-source
          fi

  workflow-notification:
    needs: update
    if: always()
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Open issue on failure or close issue on success
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          number=$(gh issue list --search "in:title Workflow failed: $GITHUB_WORKFLOW" --limit 1 --json number -q .[].number)

          success="${{ needs.update.result == 'success' }}"
          issue_body="See [$GITHUB_WORKFLOW #$GITHUB_RUN_NUMBER](https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)."

          if [[ $number ]]; then
            if [[ "$success" == "true" ]]; then
              gh issue close $number
            else
              gh issue comment $number --body "$issue_body"
            fi
          elif [[ "$success" == "false" ]]; then
            gh issue create --title "Workflow failed: $GITHUB_WORKFLOW (#$GITHUB_RUN_NUMBER)" --body "$issue_body"
          fi
